#!/usr/bin/env python3
"""Create/update the remote-state stack using the standard boto3 credential chain."""

import argparse
import json
import os
from pathlib import Path
import re
import sys
import tempfile


INFRASTRUCTURE = Path(__file__).resolve().parents[1]


def arguments(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--environment", choices=("dev", "production"), required=True)
    parser.add_argument("--region", default="ap-northeast-1")
    parser.add_argument("--allowed-account-id", required=True)
    parser.add_argument("--project", default="terutaro")
    args = parser.parse_args(argv)
    if not re.fullmatch(r"[0-9]{12}", args.allowed_account_id):
        parser.error("--allowed-account-id must contain exactly 12 digits")
    if not re.fullmatch(r"[a-z][a-z0-9-]{1,15}", args.project):
        parser.error("--project must contain 2–16 lowercase letters, numbers or hyphens")
    if not re.fullmatch(r"[a-z]{2}(?:-[a-z]+)+-[0-9]+", args.region):
        parser.error("--region must be an AWS region name")
    return args


def write_backend(path, outputs, account_id, environment):
    """Atomically replace configuration; credentials are never accepted or written."""
    content = "\n".join([
        "# Generated by infrastructure/scripts/bootstrap_backend.py. Do not commit.",
        f'bucket = {json.dumps(outputs["BackendBucketName"])}',
        f'key = {json.dumps(environment + "/terraform.tfstate")}',
        f'region = {json.dumps(outputs["BackendRegion"])}',
        f'dynamodb_table = {json.dumps(outputs["BackendLockTableName"])}',
        "encrypt = true",
        "use_lockfile = true",
        f"allowed_account_ids = [{json.dumps(account_id)}]",
        "",
    ])
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.is_symlink():
        raise ValueError("Refusing to replace a symlink backend.hcl")
    descriptor, temporary = tempfile.mkstemp(prefix=".backend-", dir=path.parent)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "w", encoding="utf-8") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def bootstrap(args, session):
    # Check the account before making any CloudFormation mutation.
    account_id = session.client("sts").get_caller_identity()["Account"]
    if account_id != args.allowed_account_id:
        raise ValueError("AWS account does not match --allowed-account-id; no stack changes made")
    client = session.client("cloudformation")
    stack_name = f"{args.project}-{args.environment}-terraform-backend"
    template = (INFRASTRUCTURE / "cloudformation/terraform-backend.yaml").read_text(encoding="utf-8")
    parameters = [
        {"ParameterKey": "Project", "ParameterValue": args.project},
        {"ParameterKey": "Environment", "ParameterValue": args.environment},
    ]
    try:
        existing = client.describe_stacks(StackName=stack_name)["Stacks"][0]
    except client.exceptions.ClientError as error:
        details = error.response.get("Error", {})
        if details.get("Code") != "ValidationError" or "does not exist" not in details.get("Message", ""):
            raise
        existing = None
    if existing is None:
        client.create_stack(
            StackName=stack_name,
            TemplateBody=template,
            Parameters=parameters,
            EnableTerminationProtection=True,
            Tags=[{"Key": "Project", "Value": args.project}, {"Key": "Environment", "Value": args.environment}],
        )
        client.get_waiter("stack_create_complete").wait(StackName=stack_name)
    else:
        if existing["StackStatus"] not in ("CREATE_COMPLETE", "UPDATE_COMPLETE", "UPDATE_ROLLBACK_COMPLETE"):
            raise ValueError(f'Stack is not ready for update: {existing["StackStatus"]}')
        try:
            client.update_stack(StackName=stack_name, TemplateBody=template, Parameters=parameters)
        except client.exceptions.ClientError as error:
            details = error.response.get("Error", {})
            if details.get("Code") != "ValidationError" or "No updates are to be performed" not in details.get("Message", ""):
                raise
        else:
            client.get_waiter("stack_update_complete").wait(StackName=stack_name)
    stack = client.describe_stacks(StackName=stack_name)["Stacks"][0]
    outputs = {entry["OutputKey"]: entry["OutputValue"] for entry in stack["Outputs"]}
    if outputs["BackendRegion"] != args.region:
        raise ValueError("Stack output region does not match the requested region")
    output_path = INFRASTRUCTURE / "terraform/environments" / args.environment / "backend.hcl"
    write_backend(output_path, outputs, account_id, args.environment)
    print(f"Stack ready: {stack_name}")
    print(f"Backend configuration written with mode 0600: {output_path}")


def main(argv=None):
    args = arguments(argv)
    try:
        import boto3
        from botocore.exceptions import BotoCoreError, ClientError
    except ImportError:
        print("Install boto3 in your Python environment before running bootstrap.", file=sys.stderr)
        return 1
    try:
        bootstrap(args, boto3.Session(region_name=args.region))
    except (BotoCoreError, ClientError, ValueError, OSError, KeyError) as error:
        # Avoid dumping requests, credential objects, or a full SDK traceback.
        print(f"Bootstrap failed: {type(error).__name__}. Check the target account, stack status and permissions.", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
