import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { Metadata } from "next";

export const SITE_URL = "https://terutaro.github.io";
export const SITE_NAME = "terutaro";
export const OG_IMAGE = { url: "/assets/og-image.png", width: 1200, height: 630, alt: "terutaro" };

export const portfolioPageNames = [
  "index",
  "works",
  "partners",
  "events",
  "columns",
  "contact",
  "pricing",
] as const;

export type PortfolioPageName = (typeof portfolioPageNames)[number];
export const portfolioLocales = ['ja', 'en', 'zh'] as const;
export type PortfolioLocale = (typeof portfolioLocales)[number];
export const localeLanguages = { ja: 'ja', en: 'en', zh: 'zh-CN' } as const;

export function portfolioPath(name: PortfolioPageName, locale: PortfolioLocale) {
  return `${locale === 'ja' ? '' : '/' + locale}/${name}.html`;
}

export interface PortfolioPageContent {
  title: string;
  description: string;
  body: string;
  scripts: string[];
}

/** Read only the local, trusted HTML generated by scripts/build.py. */
export function getPortfolioPage(name: PortfolioPageName, locale: PortfolioLocale = 'ja'): PortfolioPageContent {
  const file = join(process.cwd(), ".generated", "pages.json");
  let pages: Record<string, unknown>;

  try {
    pages = JSON.parse(readFileSync(file, "utf8"));
  } catch (error) {
    throw new Error(
      "Cannot read the generated portfolio. Run `npm run prepare:content` in frontend first.",
      { cause: error },
    );
  }

  const key = locale === 'ja' ? name : `${locale}/${name}`;
  const page = pages[key] as Partial<PortfolioPageContent> | undefined;
  if (
    !page ||
    typeof page.title !== "string" ||
    typeof page.description !== "string" ||
    typeof page.body !== "string" ||
    !Array.isArray(page.scripts) ||
    !page.scripts.every((src) => typeof src === "string" && src.startsWith("/assets/"))
  ) {
    throw new Error(`Invalid generated portfolio page: ${name}`);
  }

  return page as PortfolioPageContent;
}

export function getPortfolioMetadata(name: PortfolioPageName, locale: PortfolioLocale = 'ja'): Metadata {
  const page = getPortfolioPage(name, locale);
  const title = `${page.title} — ${SITE_NAME}`;
  const path = name === 'index' && locale === 'ja' ? '/' : portfolioPath(name, locale);
  // openGraph / twitter are not deep-merged with the layout, so each page sets the full object.
  return {
    title: { absolute: title },
    description: page.description,
    alternates: { canonical: path, languages: {
      ja: name === 'index' ? '/' : portfolioPath(name, 'ja'),
      en: portfolioPath(name, 'en'),
      'zh-CN': portfolioPath(name, 'zh'),
      'x-default': name === 'index' ? '/' : portfolioPath(name, 'ja'),
    } },
    openGraph: {
      type: "website",
      siteName: SITE_NAME,
      locale: {ja: 'ja_JP', en: 'en_US', zh: 'zh_CN'}[locale],
      url: path,
      title,
      description: page.description,
      images: [OG_IMAGE],
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: page.description,
      images: [OG_IMAGE.url],
    },
  };
}
